name: Matrix Demo
on: push
jobs:
  build:
    # even if the jobs failed continue executing other jobs
    # i.e. ubuntu-latest+node12 failed, keep running other jobs
    continue-on-error: true
    strategy:
        matrix:
            my-node-version: [12, 14, 16]
            operating-system: [ubuntu-latest, windows-latest]
            include:
                - my-node-version: 18
                  operating-system: ubuntu-latest
            exclude:
                - my-node-version: 12
                  operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.my-node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
