name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            my-artifact-name:
                description: The name of the deployable artifact files
                required: false # if true workflow will fail if not provided
                default: dist
                type: string
        secrets:
            some-secret:
                required: false
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get Artifact
              uses: actions/download-artifact@v4
              with:
                name: ${{ inputs.my-artifact-name }}
            - name: List files
              run: ls
            - name: Output Information
              run: echo "Deploying & uploading..."